language: rust
rust:
  - 1.46.0
  - beta
  - nightly
sudo: false
before_script:
  - rustup component add clippy
script:
  - cargo build --verbose
  - cargo clippy -- -D warnings
  - cargo test
notifications:
  email:
    on_success: never
