[package]
name = "cardpack"
description = "Generic Deck of Cards"
version = "0.3.9"
authors = ["folkengine <gaoler@electronicpanopticon.com>"]
repository = "https://github.com/ContractBridge/cardpack.rs.git"
homepage = "https://github.com/ContractBridge/cardpack.rs"
edition = "2018"
license = "AGPL-3.0"

[lib]
name = "cardpack"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
fluent-templates = "0.5.13"
lazy_static = "1.4.0"
rand = "0.7.3"
unic-langid = { version = "0.9.0", features = ["macros"] }