[package]
name = "cardpack"
description = "Generic Deck of Cards"
version = "0.1.0"
authors = ["folkengine <gaoler@electronicpanopticon.com>"]
edition = "2018"

[lib]
name = "cardpack"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-templates = "0.5.13"
lazy_static = "1.4.0"
rand = "0.7.3"
unic-langid = { version = "0.9.0", features = ["macros"] }