[package]
name = "spielkarten"
description = "Generic Deck of Cards"
version = "0.1.0"
authors = ["folkengine <gaoler@electronicpanopticon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-templates = "0.5.13"
unic-langid = { version = "0.9.0", features = ["macros"] }